### ISSUE TITLE
After recent update of SCB statistics more years was added, which makes SCB-based charts titles and colors inconsistent

### ISSUE THREAD

**Issue by pitber549** [morberg/covid-notebook#14]
After recent update of 
https://scb.se/hitta-statistik/statistik-efter-amne/befolkning/befolkningens-sammansattning/befolkningsstatistik/pong/tabell-och-diagram/preliminar-statistik-over-doda/
(2020-12-14-preliminar_statistik_over_doda_inkl_eng)
it was added data for years 2015 - 2017, so currently it provides 2015 - 2020 statistics (instead of 2018 - 2020 as it was before).

So that now chart titles and some series colors need to be fixed on page
https://morberg.github.io/covid-notebook/excess.html

**Comment by morberg** [comment]
Fixed
