### ISSUE TITLE
It would be nice to see more charts from `county-data.ipynb` at `morberg.github.io/covid-notebook/`

### ISSUE THREAD

**Issue by pitber549** [morberg/covid-notebook#2]
It looks like version deployed at `morberg.github.io/covid-notebook/` is not up to date (comparing to state of repository). It would  be nice to see more charts from 
https://colab.research.google.com/github/morberg/covid-notebook/blob/master/county-data.ipynb
at 
https://morberg.github.io/covid-notebook/

Very last charts chart looks especially interesting, but making a link directly to it in `.../county-data.ipynb` doesn't work.
Also I could see some similar charts at 
https://www.euromomo.eu/graphs-and-maps/#pooled-by-age-group
But as for me last chart from `county-data.ipynb` is more expressive.

**Comment by morberg** [comment]
Added two graphs from county-data. The last graph is clickable to filter on county level
