### ISSUE TITLE
It would be nice to add semi-transparent bar for latest 2-3 weeks to highlight highly preliminary data

### ISSUE THREAD

**Issue by pitber549** [morberg/covid-notebook#5]
Basing on `Tabell 8` of [SCB (Excel)](https://www.scb.se/hitta-statistik/statistik-efter-amne/befolkning/befolkningens-sammansattning/befolkningsstatistik/pong/tabell-och-diagram/preliminar-statistik-over-doda/) it is clearly seen that for latest 2 weeks provided data is highly preliminary, starting from 3-rd week before release date - data become +/- accurate (daily error <= 10), and 3 weeks back before release it is actually highly accurate. Comparing historical date with latest series it is possible to make raw estimate of systematic error (and make some simple prediction)
![2020-05-29-res-daily+err](https://user-images.githubusercontent.com/64286817/83445454-ae336280-a455-11ea-81d0-5f23e17538a6.png)
(see `Tabell 8_1` of [2020-05-29-preliminar_statistik_over_doda_inkl_eng+(31-rolling).xlsx](https://github.com/adamaltmejd/covid/files/4712986/2020-05-29-preliminar_statistik_over_doda_inkl_eng%2B.31-rolling.xlsx) ; [.ods.zip](https://github.com/morberg/covid-notebook/files/4713049/2020-05-29-preliminar_statistik_over_doda_inkl_eng%2B.31-rolling.ods.zip))

So that it would be nice to draw some semi-transparent bar in [charts](https://morberg.github.io/covid-notebook/charts/index.html) of section `Total weekly deaths 2018-2020'st`
For example for weekly lines charts it may looks like
![2020-05-29-res-weekly-no-Stockholm](https://user-images.githubusercontent.com/64286817/83446788-fc496580-a457-11ea-9ff2-bba015003e5f.PNG)

For bar charts it maybe good to add some raw prediction series to see what one could expect in reality for latest weeks.
Simple prediction could be calculated (for example) as average diff between latest serries and shifted down historical series.

**Comment by morberg** [comment]
This is the reason the latest week of data is excluded in the graph. You could exclude yet another week from the graph as an alternative. I’d rather make it simpler than more complicated.

**Comment by pitber549** [comment]
Yes, actually it is good idea (to just exclude some samples). And for making my conclusions I've also made exactly the same (exclude latest 10 days). 
But then perhaps it is reasonable to nightlight that fact in some titles (or comments) near chart, saying that "latest 1 week excluded from chart ..." etc.
Actually it is even possible to provide error estimate in that comment (after exclusion, for rightmost samples, it should be daily error <= 10 , daily sample ~= 250 ... 300 ; 10 / 250 is near 4% ; and weekly error should be even less)

**Comment by pitber549** [comment]
Yes, actually it is good idea (to just exclude some samples). And for making my conclusions I've also made exactly the same (exclude latest 10 days). 
But then perhaps it is reasonable to highlight that fact in some titles (or comments) near chart, saying that "latest 1 week excluded from chart ..." etc.
Actually it is even possible to provide error estimate in that comment (after exclusion, for rightmost samples, it should be daily error <= 10 , daily sample ~= 250 ... 300 ; 10 / 250 is near 4% ; and weekly error should be even less)

**Comment by morberg** [comment]
I’ve added an explanation in the text introducing the chart.
