### ISSUE TITLE
Chats labels "Data published ..." are no longer got updated

### ISSUE THREAD

**Issue by pitber549** [morberg/covid-notebook#7]
Some charts from folder
https://github.com/morberg/covid-notebook/tree/master/charts
has outdated label "Data published ..."
![chart-capture](https://user-images.githubusercontent.com/64286817/85312093-0a226180-b4bf-11ea-8924-4d4d6c0717cf.png)

**Comment by morberg** [comment]
Thanks for reporting. Fixed now.
